### ISSUE TITLE
Fix transaction info component on smaller screen sizes

### ISSUE THREAD

**Issue by DominikGuzei** [input-output-hk/cardano-explorer-app#114]
The `TransactionInfo` component looks broken when the window size is too small:

![screenshot 2019-11-14 um 12 47 42](https://user-images.githubusercontent.com/172414/68854750-ffa81a00-06dc-11ea-801d-c77d4b490111.png)

**Comment by DeeJayElly** [comment]
Fixed 

<img width="549" alt="Screenshot 2019-12-23 09 07 36" src="https://user-images.githubusercontent.com/15862062/71344759-b2cd2400-2563-11ea-886f-0d73b409ecf8.png">
<img width="368" alt="Screenshot 2019-12-23 09 07 22" src="https://user-images.githubusercontent.com/15862062/71344760-b365ba80-2563-11ea-8940-71fc3126d0c3.png">
