### ISSUE TITLE
Header background visual, animation and static image variant

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#137]
The specified backgrounds:
<img width="970" alt="Screenshot 2019-11-30 at 15 51 23" src="https://user-images.githubusercontent.com/303881/69895727-7d308300-1389-11ea-9477-8525182cb208.png">
<img width="1034" alt="Screenshot 2019-11-30 at 15 51 40" src="https://user-images.githubusercontent.com/303881/69895728-7d308300-1389-11ea-8f3e-f027f02578ae.png">

... are not currently implemented. The animation was causing performance issues so was initially replaced with a screen shot, but has since been removed in #136 since it was just a placeholder.

The suggestion from @DominikGuzei is to render the animation as a video, and then use a static image in the smaller footprint mode.

**Comment by DominikGuzei** [comment]
@rhyslbw i think for starters a high quality static image would already be good enough.

**Comment by a-rukin** [comment]
![testnet](https://user-images.githubusercontent.com/2539345/70927914-f2b27980-2040-11ea-8e49-8e4eda868fba.png)
![mainnet](https://user-images.githubusercontent.com/2539345/70927915-f2b27980-2040-11ea-8028-7f6542697ae6.png)
![itn](https://user-images.githubusercontent.com/2539345/70927916-f2b27980-2040-11ea-9126-ac10eba67eb9.png)

**Comment by a-rukin** [comment]
[bgs.zip](https://github.com/input-output-hk/cardano-explorer-app/files/3969314/bgs.zip)
