### ISSUE TITLE
Invalid links in the block table when viewing the Epoch details

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#138]
These links are not valid, since it leads to the same page.
<img width="670" alt="Screenshot 2019-11-30 at 16 14 27" src="https://user-images.githubusercontent.com/303881/69895914-8e2ec380-138c-11ea-863a-281b283340c2.png">

**Comment by DominikGuzei** [comment]
This was fixed by #154
