### ISSUE TITLE
Chrome dev tools audit

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#143]
The Chrome developer tools audit shows we've got some easy gains to make, in particular optimising the initial load. Please run this and act on the advice outside the scope of API interactions perf

**Comment by DominikGuzei** [comment]
@rhyslbw Lighthouse tells me the the most important optimization right now would be to enable gzip compression on the server. I will look into reducing the package sizes in the meanwhile.

**Comment by DominikGuzei** [comment]
Fixed in #151
