### ISSUE TITLE
Font implementation

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#185]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/2539345/73347008-eeac8500-4297-11ea-81f8-927ba72f3279.png">
@DeeJayElly can you pls explain me here how we use the fonts?
do we use two types like "ProximaNova-Light" and "ProximaNova-Semibold"? or we just tune the font weights? 
As I can see it's a bit different results when using font weight 🤔

_Originally posted by @a-rukin in https://github.com/input-output-hk/cardano-explorer-app/pull/180#issuecomment-579683667_

**Comment by DeeJayElly** [comment]
@rhyslbw @a-rukin  We use different types like ProximaNova-Light, ProximaNova-Bold, ProximaNova-Semibold etc. Most of them have different font-weight. Basically they are all part of the same font family but with the different weight.

I can see the difference but that's how its implemented currently.

**Comment by a-rukin** [comment]
@DeeJayElly can we use just different font families for this? instead of font-weight
I mean, as a fix

**Comment by DominikGuzei** [comment]
Hm … that's strange, shouldn't it work normally? (i mean the way it's implemented is standard, right?)

**Comment by DeeJayElly** [comment]
> Hm … that's strange, shouldn't it work normally? (i mean the way it's implemented is standard, right?)

Yeah its a standardized way. We managed to resolve the issue with font weight.
