### ISSUE TITLE
Multi-language UI components

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#190]
Visual Designs:
- https://app.zeplin.io/project/5878c3481bb7631c20cb161a/screen/5b05b3fce25151ce13d86d48
- https://app.zeplin.io/project/5878c3481bb7631c20cb161a/screen/5d63b15b38345e9b5a6d7de0

@DominikGuzei will advise on where to add the components, but this is not a blocker to begin development

**Comment by DeeJayElly** [comment]
UI is implemented @DominikGuzei @rhyslbw @a-rukin
