### ISSUE TITLE
Refined search helper UI

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#191]
https://app.zeplin.io/project/5878c3481bb7631c20cb161a/screen/5d63da13ff86179b0c157ddb

Searching for a block within an epoch is not a valid use-case. It's a concept that works with slots, however we are not exposing this since it is not the primary identifier for blocks. The UI should ask the user to choose if they intent to lookup a block or epoch when the number overlaps (all blocks up to the current epoch).

**Comment by a-rukin** [comment]
you can't search for all blocks "1024" for example, as they are present in all epochs. So, in this case, there would be an error that "multiple results matching search query".
The way we work with numbers is that we suggest searching in the epoch with this number. 
Block part can be empty -> than we show epoch overview
Block part filled -> we show exact block info in the specified epoch

**Comment by rhyslbw** [comment]
The UI designs are based on the idea of using a **slot**, which is not the known identifier, so the intention here is to change the UI designs to reflect this. 
 
> you can't search for all blocks "1024" for example, as they are present in all epochs
There is only one _block_ 1024. There are many slot 1024s, but as above, this is irrelevant to the user as the identifier is block number.

> there would be an error that "multiple results matching search query".
We need to capture the user's intent before the request is made. If there is overlap in the number range (currently on the mainnet there is overlap up to 175), we need to ask the user a question "Block or epoch?"

Also it's worth noting here that it's not really a search, but a _lookup_. So right now if the number matches an epoch, we look that up.

**Comment by rhyslbw** [comment]
Nice work on the update @a-rukin. It's probably better to read "Search for epoch 12" and "Search for block 12", omitting the "an"

**Comment by rhyslbw** [comment]
@DeeJayElly I've assigned this to you for the component implementation

**Comment by a-rukin** [comment]
> Nice work on the update @a-rukin. It's probably better to read "Search for epoch 12" and "Search for block 12", omitting the "an"

Probably 🤷‍♂

**Comment by DeeJayElly** [comment]
@rhyslbw @a-rukin @DominikGuzei done
