### ISSUE TITLE
Pagination arrow hover styling

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#195]
![Arrows2](https://user-images.githubusercontent.com/303881/74621820-87953880-5192-11ea-9a59-468893514f42.png)

Should be https://app.zeplin.io/project/5878c3481bb7631c20cb161a/screen/5d63f0cb91c8889afa5ce2a1

**Comment by DeeJayElly** [comment]
@rhyslbw @DominikGuzei done
