### ISSUE TITLE
Erroneous subheading on homepage, invalid styling of the downward arrow element

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#196]
![MainPage](https://user-images.githubusercontent.com/303881/74622052-81ec2280-5193-11ea-9edc-319288c528cb.png)

Should be:
https://app.zeplin.io/project/5878c3481bb7631c20cb161a/screen/5b05b3fce25151ce13d86d48

**Comment by DeeJayElly** [comment]
@rhyslbw @DominikGuzei done

**Comment by a-rukin** [comment]
@rhyslbw @DeeJayElly this is a look when we have only basic functionality. When we will have staking, this image posted in description becomes true (with one more element in the menu)
