### ISSUE TITLE
Component misalignment 

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#197]
![Align](https://user-images.githubusercontent.com/303881/74656269-e7ff9680-51e1-11ea-9648-f45fa9f4e322.png)
![image (6)](https://user-images.githubusercontent.com/303881/74656280-edf57780-51e1-11ea-9bf4-16ae7af2ebda.png)

**Comment by DeeJayElly** [comment]
This is completed with footer updates. @rhyslbw @DominikGuzei @a-rukin .

@a-rukin please recheck and let me know if you spot some misalignment somewhere else.

**Comment by DeeJayElly** [comment]
This is the current look and feel.

![screencapture-localhost-4000-2020-02-20-20_38_07](https://user-images.githubusercontent.com/15862062/74973645-14a2f080-5424-11ea-847b-b7ef1212fcdd.png)

**Comment by a-rukin** [comment]
@DeeJayElly alignment looks good
One small note: triangle in minimised header is filled -> should be outlined (ex https://zpl.io/V0mozqw )

**Comment by DeeJayElly** [comment]
@a-rukin fixed
