### ISSUE TITLE
Footer text wrapping

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#198]
![More About Cardano](https://user-images.githubusercontent.com/303881/74656415-2e54f580-51e2-11ea-89ed-7ba85174d96b.png)

Should be:
https://app.zeplin.io/project/5878c3481bb7631c20cb161a/screen/5de64e74f9bf2956a897cc0a

**Comment by DeeJayElly** [comment]
Done @rhyslbw @DominikGuzei
