### ISSUE TITLE
Outdated Browser page styling and missing footer

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#200]
![2020-02-11_13-09-48](https://user-images.githubusercontent.com/303881/74656885-2d709380-51e3-11ea-8050-bdbdf86a107c.png)

Should be:
https://app.zeplin.io/project/5878c3481bb7631c20cb161a/screen/5d65438ddd6f4cb2bf746a61

**Comment by DeeJayElly** [comment]
@rhyslbw @DominikGuzei @a-rukin done
