### ISSUE TITLE
Search bar and button style

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#201]
Underline colour is wrong, and the button should be only outlined when not on the homepage:

![SearchBox1](https://user-images.githubusercontent.com/303881/74657343-239b6000-51e4-11ea-8d17-3c448f83f183.png)

Should be:
https://app.zeplin.io/project/5878c3481bb7631c20cb161a/screen/5b05b3fce25151ce13d86d48
https://app.zeplin.io/project/5878c3481bb7631c20cb161a/screen/5b06e4704f55d1ef1b1df81d

**Comment by DeeJayElly** [comment]
@rhyslbw @DominikGuzei DONE and MERGED to dev
