### ISSUE TITLE
Erroneous space after ellipsis in long address display

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#202]
![Ellipsis](https://user-images.githubusercontent.com/303881/74657748-fd29f480-51e4-11ea-8276-f47bde2d7e0d.png)
Should be:
https://app.zeplin.io/project/5878c3481bb7631c20cb161a/screen/5b06e47090d3b1842141a373

**Comment by DeeJayElly** [comment]
This is fixed @rhyslbw @DominikGuzei @a-rukin
