### ISSUE TITLE
Fix latest epoch circle animation in Firefox

### ISSUE THREAD

**Issue by DominikGuzei** [input-output-hk/cardano-explorer-app#240]
In Firefox 72 the animation of the latest epoch circle is not working.

**Comment by DeeJayElly** [comment]
@DominikGuzei tried everything but it didnt work out. It seems that we need external library for this, like: https://codeburst.io/animating-react-components-with-css-and-styled-components-cc5a0585f105

**Comment by DominikGuzei** [comment]
Will look into it 👍

**Comment by DominikGuzei** [comment]
@DeeJayElly the problem is very simple: Firefox doesn't yet support `conic-gradient` ( see at bottom for compatibility: https://developer.mozilla.org/en-US/docs/Web/CSS/conic-gradient)

**Comment by DominikGuzei** [comment]
@rhyslbw @a-rukin is it ok if we postpone this after MVP … Firefox seems to be in the process of implementing the required `conic-gradient` css feature soon (it's in nightly behind a flag already): https://bugzilla.mozilla.org/show_bug.cgi?id=1175958

**Comment by DominikGuzei** [comment]
It's probably easier to fix this by using SVG

**Comment by a-rukin** [comment]
> It's probably easier to fix this by using SVG

do you need it for all three themes?
and which parts? 
only circle with gradient?

**Comment by DominikGuzei** [comment]
Im looking for easier solutions, like a polyfill: https://leaverou.github.io/conic-gradient/

**Comment by DominikGuzei** [comment]
@a-rukin ok the polyfill didn't work … let's use SVG - i only need the circle with conic gradient 👍

**Comment by DominikGuzei** [comment]
This is how it is currently rendered in Chrome:
![CleanShot 2020-03-20 at 10 57 28](https://user-images.githubusercontent.com/172414/77153192-a50f3800-6a99-11ea-941e-fb8b48f7fb18.png)

**Comment by a-rukin** [comment]
@DominikGuzei is the one from Zeplin works?

**Comment by DominikGuzei** [comment]
Design reference for this issue: https://app.zeplin.io/project/5878c3481bb7631c20cb161a/screen/5d63a2575cc9e39b8ae43af6
