### ISSUE TITLE
Byron Explorer. Explorer's Tab is missing key when Japanese is selected.

### ISSUE THREAD

**Issue by DmitriiGaico** [input-output-hk/cardano-explorer-app#248]
When Japanese language is selected the Tab looks incorrect. 
Can be reproduced for both MainNet / TestNet
![image](https://user-images.githubusercontent.com/45355947/76850343-dc8aa400-684f-11ea-89a4-b40c85dbc346.png)

**Comment by DominikGuzei** [comment]
Was fixed by #253
