### ISSUE TITLE
Byron Explorer. Misplaced Space.

### ISSUE THREAD

**Issue by DmitriiGaico** [input-output-hk/cardano-explorer-app#256]
A misplaced space in Text.
![image](https://user-images.githubusercontent.com/45355947/76975721-9f9bdb80-693b-11ea-8973-a330268c8187.png)

**Comment by DeeJayElly** [comment]
> A misplaced space in Text.
> ![image](https://user-images.githubusercontent.com/45355947/76975721-9f9bdb80-693b-11ea-8973-a330268c8187.png)

Fixed on another branch -> PR is : https://github.com/input-output-hk/cardano-explorer-app/pull/254
