### ISSUE TITLE
Handle multiple clicks when browsing

### ISSUE THREAD

**Issue by DominikGuzei** [input-output-hk/cardano-explorer-app#268]
Currently the UX is chaotic: When you click the left or right arrow multiple times (fast) then the pages are decremented or incremented but the loading is lagging behind (and when finished it shows only the next page and doesn't reflect the correct page anymore)

There are two options to fix this:
1. Disable the pagination arrows while loading next / previous page
2. Cancle the current request and send a new one for each click

**Comment by DominikGuzei** [comment]
@a-rukin what are your ideas about this?

**Comment by a-rukin** [comment]
I think that 2nd option is a bit more friendly, as blocking may piss user in cases he needs more than 1 click 🤷‍♂

**Comment by a-rukin** [comment]
So my idea was to have content in a sync with page number ))
