### ISSUE TITLE
Cleanup Footer Links

### ISSUE THREAD

**Issue by tatyanavych** [input-output-hk/cardano-explorer-app#302]
1. At the bottom right corner of the Explorer screen there is a list that includes `Cardano SL Source` item with a relevant link. Remove or replace as needed. Review the list and the links whether there are other obsolete ones.

> #### More about Cardano
> Shelley Explorer
> Cardano Foundation
> Documentation
> Cardano SL Source
> Why Cardano
> Ouroboros Algorithm

![explorer_1 0 0-rc2 20200520](https://user-images.githubusercontent.com/28982380/82430919-e4e8a080-9a85-11ea-8564-4b674bd2590d.png)

2. Do `grep -ir "Cardano SL" ${cardano_explorer_app_dir}` and `grep -ir "cardano-sl" ${cardano_explorer_app_dir}` to find all occurrences of the old stuff and replace or remove taking care of the context too.

**Comment by DominikGuzei** [comment]
@tatyanavych I'm not sure what exactly needs to be done here. Should `Cardano SL Source` be removed/replaced by something else?

All these links have been given to us as part of the design specification and are linked to the respective websites (or do I miss something?)

**Comment by rhyslbw** [comment]
@DominikGuzei Tatyana is just pointing out the issue of linking to the archived repo. I've asked for advice, but we should just make the following changes then adjust if needed:

- Shelley Explorer -> _Remove_
- Cardano SL Source -> Cardano Source linking to https://github.com/input-output-hk which has the pinned repositories

![Screenshot from 2020-06-30 14-29-59](https://user-images.githubusercontent.com/303881/86083697-559bc780-bade-11ea-8cc9-7423a7cc87d2.png)

**Comment by DominikGuzei** [comment]
Thanks @rhyslbw, will implement these changes 👍
