### ISSUE TITLE
Explorer Transaction view amounts misleading

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-explorer-app#304]
I was trying to debug where a change address ended up from the explorer and failed miserably. I ended opening up postgres and doing the queries manually. This is not the transaction I was debugging, but shows the same behavior:
https://explorer.cardano.org/en/transaction/?id=c06157e877c72be85361b0050271310f4b9620b93fd8a84414d2fdea0eb2dc98

My assumption was next to the outputs would be the amounts going to each of the addresses they were next to. This ended up being an incorrect assumption, which I think is a bug.

Here's a list of the queries if it helps I made to get the answer I was looking for (how much ada was sent to the outputs of the transaction):

Get the tx_id:
```
cexplorer=# SELECT * FROM tx WHERE hash=decode('c06157e877c72be85361b0050271310f4b9620b93fd8a84414d2fdea0eb2dc98', 'hex');
   id    |                                hash                                |  block  |  fee   |  out_sum   | size 
---------+--------------------------------------------------------------------+---------+--------+------------+------
 2007257 | \xc06157e877c72be85361b0050271310f4b9620b93fd8a84414d2fdea0eb2dc98 | 4086311 | 179288 | 8284920712 |  225
(1 row)
```

Get the tx inputs:
```
SELECT * FROM tx_in WHERE tx_in_id=2007257;
   id    | tx_in_id | tx_out_id | tx_out_index 
---------+----------+-----------+--------------
 4050460 |  2007257 |   1128450 |            1
 4050461 |  2007257 |   1232938 |            2
```
Get the addresses and values of inputs (these values are what show up in explorer interface):
```
cexplorer=# SELECT * FROM tx_out WHERE tx_id=1128450 AND index=1;
   id    |  tx_id  | index |                           address                           |   value    
---------+---------+-------+-------------------------------------------------------------+------------
 2537868 | 1128450 |     1 | Ae2tdPwUPEZ5P6QnkfF3ZW2QEK7ob5VRocxVpWtDQ1U29jznPWfiKP7eK6c | 1291200000
(1 row)

cexplorer=# SELECT * FROM tx_out WHERE tx_id=1232938 AND index=2;
   id    |  tx_id  | index |                           address                           |   value    
---------+---------+-------+-------------------------------------------------------------+------------
 2787111 | 1232938 |     2 | Ae2tdPwUPEZK4sg8PGJB2RABqwQj4rC4PMUMFxXzsehqYmyp4QdN86qWe3J | 6993900000
(1 row)
```

Get the outputs:
```
cexplorer=# SELECT * FROM tx_out WHERE tx_id=2007257;
   id    |  tx_id  | index |                                                 address                                                  |   value    
---------+---------+-------+----------------------------------------------------------------------------------------------------------+------------
 4635572 | 2007257 |     0 | DdzFFzCqrhsu5wVeit7MKhwCuGRGhy6pra1RuMtuhScF3Tpp9W5rwzLMwjBvAxNcMtBUj9cxeRjKrqUUGs2WXEtLT1MweRZ9XNnDGVbM | 5000000000
 4635573 | 2007257 |     1 | Ae2tdPwUPEZ5P6QnkfF3ZW2QEK7ob5VRocxVpWtDQ1U29jznPWfiKP7eK6c                                              | 3284920712
(2 rows)
```

It seems to be it would make more sense if the values on the right side of the screen were the values in this last query (5000000000 and 3284920712).

**Comment by rhyslbw** [comment]
It was actually changed in https://github.com/input-output-hk/cardano-explorer-app/pull/295 to implement the brief, which in this case is based on the legacy explorer. See https://github.com/input-output-hk/cardano-explorer-app/issues/294. 

Seeing the _Transaction Output_ values would be a good upgrade though, so will reference this in a feature request tracked externally.
