### ISSUE TITLE
Epochs not loading from other Epoch page

### ISSUE THREAD

**Issue by pannenkoekenpan** [input-output-hk/cardano-explorer-app#312]
When you epoch's are searched from another epoch page, the page does not load and the animation remains. 

For example: you type "150" and click on "Epoch 150". The page loads (swiftly), Therafter you type "100", and click on "Epoch 100", the loading animation remains. Only after refreshing the URL, Epoch 100 loads. 

I've not tested this with Transactions.

**Comment by rhyslbw** [comment]
Fix has been deployed to the [mainnet instance](https://explorer.cardano.org/). Thanks for reporting @pannenkoekenpan
