### ISSUE TITLE
URL with params is reset to base path

### ISSUE THREAD

**Issue by DominikGuzei** [input-output-hk/cardano-explorer-app#325]
When attempting to open a URL with parameters it reverts to the base URL (i.e. https://explorer.cardano.org/en/). It's still possible to search for the parameter just fine and the URL returned is the same as the one I had previously tried.

**Comment by DominikGuzei** [comment]
@rhyslbw I looked into this issue and realized that removing the trailing slashes in #317 resulted in this bug because our deployment server only handled `index.html` files within folders by default.

e.g: the route `/de/block/` is automatically interpreted as `/de/block/index.html` by any standard web server … but `/de/block` is expecting a `/de/block` file (because of a missing rewrite rule for this non-default behavior)

So we have two options:

1. We update the deployment server to handle these cases (e.g: `/de/block` should be rewritten to `/de/block.html`)
2. We switch back to trailing slashes – but only for production deployments (as #317 was only a fix for dev mode)

**Comment by rhyslbw** [comment]
@DominikGuzei Agree. I'll follow it up

**Comment by alan-mcnicholas** [comment]
Tested against MC4 explorer and happy to report this is now functioning correctly, thanks!
