### ISSUE TITLE
Split slots and blocks into separate columns

### ISSUE THREAD

**Issue by DominikGuzei** [input-output-hk/cardano-explorer-app#335]
In Shelley, the number of slots and blocks per epoch will never match so the current way we display `blocks / epochs` doesn't really make sense anymore. What we need instead is to display the _expected_ number of blocks within an epoch (and not use the slots value anymore)

**Comment by rhyslbw** [comment]
The expected number of blocks is probabilistic, so it's not practical to achieve what we want here. Instead, let's display each value in separate columns to remove the direction of the blocks being a 1:1 target with slots.
