### ISSUE TITLE
Bech32 addresses not accepted by search, but can be directly accessed via the URL params

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-explorer-app#342]
I got problems when querying new addresses. 

When opening: https://explorer.cardano.org/en/address.html?address=addr1q8cs8j8rv43v59ggt9zhjhngltt7qnz47zc6ypysptzd5p8kf0aj8j5dkt80t5232tf2gj28wy3hzxxam6dre965k6eslaw3az 

and pasting the address: `addr1q88fhf8v0tcckkw7xee66l3zeq5sg2uwmevazdkuqtvj8xlkf0aj8j5dkt80t5232tf2gj28wy3hzxxam6dre965k6esxhunym`
 
I am receiving:

> SORRY, WE COULD NOT FIND ANY RESULTS MATCHING:
> addr1q88fhf8v0tcckkw7xee66l3zeq5sg2uwmevazdkuqtvj8xlkf0aj8j5dkt80t5232tf2gj28wy3hzxxam6dre965k6esxhunym

URL: https://explorer.cardano.org/en/no-search-results?query=addr1q88fhf8v0tcckkw7xee66l3zeq5sg2uwmevazdkuqtvj8xlkf0aj8j5dkt80t5232tf2gj28wy3hzxxam6dre965k6esxhunym 

but when manually changing to:  https://explorer.cardano.org/en/address.html?address=addr1q88fhf8v0tcckkw7xee66l3zeq5sg2uwmevazdkuqtvj8xlkf0aj8j5dkt80t5232tf2gj28wy3hzxxam6dre965k6esxhunym 

it returns results.

**Comment by alan-mcnicholas** [comment]
Closing as this has been fixed in the 1.0.2 release
