### ISSUE TITLE
Reward withdrawals and stake addresses are not found or included in the UI

### ISSUE THREAD

**Issue by ntfreem** [input-output-hk/cardano-explorer-app#352]
**Summary**

The Cardano explorer does not show withdrawals, in particular, ITN rewards. So upon initial analysis of inputs and outputs, some transactions look unbalanced.

It is believed that this is an outcome of rewards received (probably due to staking) to an address.

**Steps to reproduce**

https://explorer.cardano.org/en/address.html?address=addr1qy2d6t0rw32wu9yxhwx3a9hzt7tzwysy4ymlk6nh62f45z9ms7x7wfk2xmekqj76value5k8ppjggssnkvpwal0cyq9qmktzym

block 4603616 8f68695f7d8f34e2bf86d0aa80da4868ada6f52c6dd1bc925b0dee53c50ca13c, tx 0b8c5be678209bb051a02904dd18896a929f9aca8aecd48850939a590175f7e8

**Expected results**

All rewards received from staking should be seen and included in the UTXO distribution and marked accordingly, a field representing rewards in the transaction structure, something to verify that it’s a legal transaction.

**Actual results**

At the moment there is no indication of any reward transaction or otherwise. Instead, we only see a balance increase.

**Conclusion**

In principle, addresses that exchanges own should not have any withdrawals on rewards.. unless they have explicitly made them

But it's agreed that the explorer should also report withdrawals

**Comment by rhyslbw** [comment]
Thanks @ntfreem. I'm working on this now, but just want to clarify some points raised:


> It is believed that this is an outcome of rewards received (probably due to staking) to an address.

The transactions are being constructed with funds from the rewards account.

> All rewards received from staking should be seen... a field representing rewards in the transaction structure

We're currently limited to only showing _withdrawals_, which is usually the act of spending from the rewards account

> and included in the UTXO distribution

This is already the case.
