### ISSUE TITLE
Pagination appears to be returning perPage+1 elements

### ISSUE THREAD

**Issue by alan-mcnicholas** [input-output-hk/cardano-explorer-app#360]
https://cardano-explorer-mainnet.netlify.app/en/browse-epochs?page=21&perPage=10

Possibly by design for readability but the UI does not appear to be following the pagination parameter provided, it is always displaying perPage+1.

Versiosn: https://github.com/input-output-hk/cardano-explorer-app/releases/tag/vNext

**Comment by rhyslbw** [comment]
This is expected. The pagination was slightly more complicated than we wanted, and this is an unfortunate trade-off.
