### ISSUE TITLE
Can't find newly generated paper wallet address (Yoroi) within cardano explorer but found it on cardanoscan

### ISSUE THREAD

**Issue by Man7hano** [input-output-hk/cardano-explorer-app#381]
Hey guys, I have just created a new paper wallet for my friend's newborn. But I couldn't' find the wallet address on https://explorer.cardano.org/en but I was able to find it on https://cardanoscan.io/ .

It made me a bit suspicious so please fix the explorer. I am not sure what the issue causes but I can help as well.

The address is: Ae2tdPwUPEZ4umTvC7khCGvCtVHhDzPY2dkjhSgx2m4rSjiveD3z8AkRs24

Happy coding...

**Comment by Man7hano** [comment]
I have now transferred 200 ADA to the wallet and now I can find it. Could it be that only active wallets are found?

**Comment by rhyslbw** [comment]
Creating an address is an offline operation, and does not appear on the chain until funds are sent to it.
