### ISSUE TITLE
Small screen size styling when non-ada tokens are present

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#395]
![image](https://user-images.githubusercontent.com/303881/112443717-62192c00-8da1-11eb-8dcb-8ad68dc1ce12.png)

**Comment by morrigan** [comment]
+1 for this!

Native token names should be clearly visible in the app as it is the UX that user is expecting rather than some identification numbers. Should be simple enough to update so I hope this will take priority as currently it is almost unusable.

**Comment by rhyslbw** [comment]
Thanks for the input @morrigan.

> Native token names should be clearly visible in the app as it is the UX that user is expecting rather than some identification numbers

We support for showing metadata from the off-chain service managed by the Cardano Foundation, which will hopefully be live and populated by policy owners soon: https://github.com/cardano-foundation/cardano-token-registry

The name you're referring to intended to be a policy sub-identifier, or to encode properties for machine interpretation. Other products that choose to decode and display the value as a "name" are doing so at the risk of their users being spoofed with `assetName` being set as, for example, 'ada`.

This is discussed in https://github.com/cardano-foundation/CIPs/pull/64
