### ISSUE TITLE
PolicyId is missing for fingerPrint calculation

### ISSUE THREAD

**Issue by yanisurbis** [input-output-hk/cardano-explorer-app#410]
Fingerprints are different for different explorers. Please take a look at [this](https://cardano.stackexchange.com/questions/2030/did-the-token-fingerprint-hash-algorithm-change/2050#2050) question on CardanoExchange.

**Comment by rhyslbw** [comment]
Fixed in https://github.com/input-output-hk/cardano-graphql/pull/526
