### ISSUE TITLE
Address does not exist error on address that does exist

### ISSUE THREAD

**Issue by eddex** [input-output-hk/cardano-explorer-app#412]
Version: 1.5.0
Network: Testnet (https://explorer.cardano-testnet.iohkdev.io)

**Description**
When inspecting an address, an "ADDRESS DOES NOT EXIST" error appears.

![image](https://user-images.githubusercontent.com/5302085/124382325-1c84cd00-dcc7-11eb-86ae-684eea0f5c7e.png)

**Steps to reproduce**
I faced this problem on the testnet, therefore the steps are for the testnet too:
1. Open a block: https://explorer.cardano-testnet.iohkdev.io/en/block?id=37e2aeb9b0b22b900caa0cf1b25abd67c193db21710bb3c5a16025d2693eb87f
2. Click on an address that was involved in a transaction. The following 2 are part of the block in step 1:
  - https://explorer.cardano-testnet.iohkdev.io/en/address?address=addr_test1qpmtp5t0t5y6cqkaz7rfsyrx7mld77kpvksgkwm0p7en7qum7a589n30e80tclzrrnj8qr4qvzj6al0vpgtnmrkkksnqd8upj0
  - https://explorer.cardano-testnet.iohkdev.io/en/address?address=addr_test1qpmtp5t0t5y6cqkaz7rfsyrx7mld77kpvksgkwm0p7en7qum7a589n30e80tclzrrnj8qr4qvzj6al0vpgtnmrkkksnqd8upj0

**Expected behavior**
- The page shows information about the address

**Actual behavior**
- The page shows an "ADDRESS DOES NOT EXIST" error.

**Comment by itmilosIOHK** [comment]
We have the same issue with https://github.com/input-output-hk/cardano-explorer-app/issues/415

**Comment by rhyslbw** [comment]
It will be resolved the update to cardano-graphql@5.0.0, which is being prepared in: #414

**Comment by rhyslbw** [comment]
Resolved in https://github.com/input-output-hk/cardano-explorer-app/releases/tag/1.6.0

**Comment by itmilosIOHK** [comment]
hi @rhyslbw, I tried looking for 
addr1q8kpvxkanzeqjdg4lxl0cddjhkrt5875l2hc70l6umnsewktvxgv2xaqvtrvy0c0qjahwdzfq0v8tspchad3k9lsmtcssycwfa
on https://explorer.cardano.org/en/address.html and returned ADDRESS DOES NOT EXIST:

**Comment by rhyslbw** [comment]
@itmilosIOHK 

The deployment was updated after you commented. The version can be observed here:
![image](https://user-images.githubusercontent.com/303881/127455541-318453e0-c868-4e10-b3d1-e8df456ee461.png)
