### ISSUE TITLE
Assigning empty Block.slotNo to 0 is invalid

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#69]
https://github.com/input-output-hk/cardano-explorer-app/blob/ec1281ab9f1664edc64eabcf37245c5e5b537b2b/source/features/blocks/api/transformers.ts#L12

https://github.com/input-output-hk/cardano-graphql/blob/develop/src/schema.graphql#L251-L254

**Comment by DominikGuzei** [comment]
Yeah but what would be valid instead, empty string?

**Comment by rhyslbw** [comment]
Yes, just a blank string
